Class Demo.Operations.PDF.PDFRequest Extends (%Persistent, Ens.Request)
{

Storage Default
{
<Data name="PDFRequestDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^Demo.Operations98A3.PDFRequestD</DataLocation>
<DefaultData>PDFRequestDefaultData</DefaultData>
<IdLocation>^Demo.Operations98A3.PDFRequestD</IdLocation>
<IndexLocation>^Demo.Operations98A3.PDFRequestI</IndexLocation>
<StreamLocation>^Demo.Operations98A3.PDFRequestS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
